### ISSUE TITLE
java.lang.RuntimeException: Missing event detected.

### ISSUE THREAD

**Issue by A-legac45** [milaboratory/docs#59]
Hello, 

I run mixcr on all my bulk mi laboratories tcr data but I encounter a problem for two of them. Do you know what happen? Does somebody already encounter this message?

Many thanks

**My code:**

/Users/alegac/opt/anaconda3/pkgs/mixcr-4.4.1-0/bin/mixcr -Xmx15g analyze milab-human-rna-tcr-umi-multiplex /Users/alegac/Documents/bulk_tcr/S1/s1_trimmed_R1.fastq.gz  /Users/alegac/Documents/bulk_tcr/S1/s1_trimmed_R2.fastq.gz /Users/alegac/Documents/bulk_tcr/S1/results_01    

**My error :** 

Writing pre-clones: 72%  ETA: 00:01:20
Writing pre-clones: 82,4%  ETA: 00:00:44
Writing pre-clones: 92,7%  ETA: 00:00:17
Writing pre-clones: 40,6%
Initialization: progress unknown
4.4.1; built=Thu Jul 06 19:36:41 CEST 2023; rev=f7cd556c6c; lib=repseqio.v3.0.1
picocli.CommandLine$ExecutionException: Error while running command assemble java.lang.RuntimeException: Missing event detected.
	at com.milaboratory.mixcr.cli.Main.registerExceptionHandlers$lambda-12(SourceFile:323)
	at picocli.CommandLine.execute(CommandLine.java:2088)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd$PlanBuilder.executeSteps(SourceFile:470)
	at com.milaboratory.mixcr.cli.CommandAnalyze$Cmd.run0(SourceFile:412)
	at com.milaboratory.mixcr.cli.MiXCRCommand.run(SourceFile:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at com.milaboratory.mixcr.cli.Main.registerLogger$lambda-26(SourceFile:426)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at com.milaboratory.mixcr.cli.Main.main(SourceFile:98)
Caused by: java.lang.RuntimeException: Missing event detected.
	at com.milaboratory.o.hN.a(SourceFile:59)
	at com.milaboratory.o.hT$c.accept(SourceFile:1484)
	at cc.redberry.pipe.blocks.FilteringPort.take(FilteringPort.java:65)
	at cc.redberry.pipe.blocks.O2ITransmitter.run(O2ITransmitter.java:63)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by mizraelson** [comment]
Hi, could you please confirm if the issue still persists with the latest MiXCR version? If it does, would it be possible for you to share the file that's causing the error?

**Comment by A-legac45** [comment]
[results_05.align.report.txt](https://github.com/milaboratory/docs/files/12249571/results_05.align.report.txt)
[results_05.refine.report.txt](https://github.com/milaboratory/docs/files/12249572/results_05.refine.report.txt)

I can not upload my files there are two big unfortunatly

**Comment by mizraelson** [comment]
Maybe you can share through Google drive or we can provide an sftp for upload?

**Comment by mizraelson** [comment]
Could you please try running the problematic files with version 4.4.2 to confirm if the issue still persists?

**Comment by A-legac45** [comment]
Yes I can try this I will install mixcr4.4.2

**Comment by mizraelson** [comment]
Great, let me know how it works.

**Comment by A-legac45** [comment]
Ok thanks

**Comment by A-legac45** [comment]
Unfortunately I do not know why but I works for one sample the update of mixcr but not for the other I still have the same error message when I run this

 /Users/alegac/Downloads/mixcr-4.4.2/mixcr -Xmx20g analyze milab-human-rna-tcr-umi-multiplex /Users/alegac/Documents/bulk_tcr/D1454T09/D1454T09_trimmed_R1.fastq.gz  /Users/alegac/Documents/bulk_tcr/D1454T09/D1454T09_trimmed_R2.fastq.gz /Users/alegac/Documents/bulk_tcr/D1454T09/results_09 -f

Do you have any idea but my last problem?

**Comment by mizraelson** [comment]
Hi. Is it possible to share the problematic sample with us, so I can reproduce and investigate?

**Comment by A-legac45** [comment]
I ask my collegue if I can share and let you know

**Comment by A-legac45** [comment]
| http://xfer.curie.fr/get/My2aUMCB43v/D1454T09_trimmed_R1.fastq.gz
-- | --


http://xfer.curie.fr/get/tQXbJ0J9Az5/D1454T09_trimmed_R2.fastq.gz

http://xfer.curie.fr/get/bNw50aOlQ2M/results_09.align.report.txt

http://xfer.curie.fr/get/MlMfKbgd59c/results_09.align.report.json

http://xfer.curie.fr/get/KeJFDbWFFmx/results_09.refine.report.txt


http://xfer.curie.fr/get/CzUGjlKVO1T/results_09.refine.report.json

http://xfer.curie.fr/get/EL5jaDemfb8/results_09.vdjca

http://xfer.curie.fr/get/3iHQ2O2MTCp/results_09.refined.vdjca

MERCI.  PAR AVANCE

**Comment by mizraelson** [comment]
Hi,
I wasn't able to replicate the error on my side. The command finished with no errors.

```
mixcr -Xmx100G analyze milab-human-rna-tcr-umi-multiplex \
D1454T09_trimmed_R1.fastq.gz \
D1454T09_trimmed_R2.fastq.gz \
output
``` 
[Archive.zip](https://github.com/milaboratory/docs/files/12322271/Archive.zip)

Please find the clonotype table attached. All the reports look good. Can you try to run it again?

**Comment by A-legac45** [comment]
Hi, 

Super many thanks 

I just try running it one more time 

/Users/alegac/Downloads/mixcr-4.4.2/mixcr -Xmx22g analyze milab-human-rna-tcr-umi-multiplex /Users/alegac/Documents/bulk_tcr/D1454T09/D1454T09_trimmed_R1.fastq.gz  /Users/alegac/Documents/bulk_tcr/D1454T09/D1454T09_trimmed_R2.fastq.gz /Users/alegac/Documents/bulk_tcr/D1454T09/results_09 -f

I let you know if it work.
